Polish error messages

diff --git a/validate-pull-secret b/validate-pull-secret
--- a/validate-pull-secret
+++ b/validate-pull-secret
@@ -28,12 +28,14 @@ print_help() {
 	echo -e 'Usage:'
 	echo -e "${0} [-i release_image] authfile"
 	# shellcheck disable=SC2016
-	echo -e '\t-i\tSpecify the release image to be used in the build. By default, the image is determined using `openshift-install`, which must be in $PATH'
+	echo -e '\t-i\tSpecify the release image to be used in the build. By default, the image is determined using `openshift-install`, provided it is in $PATH'
 	echo -e '\tauthfile\tPath of the pull secret.'
 	echo -e '\t-h\tPrint this help'
 }
 
 unknown_flag() {
+	echo 'Fatal error: unknown flag.'
+	echo
 	print_help
 	exit 2
 }
@@ -102,7 +104,7 @@ fi
 # If release_image is not specified with the "-i" flag, then ask openshift-install
 release_image="${release_image:-$(get_installer_release_image)}"
 if [ -z "$release_image" ]; then
-	>&2 echo 'Could not find the release image'
+	>&2 echo ' Fatal error: Could not find the release image'
 	exit 2
 fi
 >&2 echo "Using release image: ${release_image}"
@@ -121,6 +123,8 @@ while read -r line; do
 	if skopeo inspect --authfile "${authfile}" "docker://${image_from}" >/dev/null; then
 		echo "OK"
 	else
+		echo
+		echo "Failed image URL: $image_from"
 		exit 1
 	fi
 done < "$parsed_lines"
