Allow passing the image directly
With the `-r` (for Release) switch.

diff --git a/validate-pull-secret b/validate-pull-secret
--- a/validate-pull-secret
+++ b/validate-pull-secret
@@ -2,11 +2,21 @@
 
 set -Eeuo pipefail
 
-declare release_image='' authfile=''
+declare release_image='' installer='' authfile=''
 
+# Get the installer release image from the passed binary, or from the one
+# available in $PATH
 get_installer_release_image() {
 	declare installer
-	installer="$(command -v 'openshift-install')" || { return 0; }
+	installer="$1"
+
+	if [ -z "$installer" ]; then
+		installer="$(command -v 'openshift-install')" || return 0;
+	else
+		if ! [ -x "$installer" ]; then
+			return 0
+		fi
+	fi
 
 	"$installer" version | grep 'release image' | cut -d ' ' -f3
 }
@@ -23,13 +33,16 @@ print_help() {
 	echo -e '\t* jq [ https://stedolan.github.io/jq ]'
 	echo -e '\t* podman'
 	echo -e '\t* skopeo'
-	echo -e '\t* openshift-installer for automatic image detection (required if "-i" is not used)'
+	echo -e '\t* openshift-installer for automatic image detection (required unless "-r" is used)'
 	echo
 	echo -e 'Usage:'
 	echo -e "${0} [-i release_image] authfile"
 	# shellcheck disable=SC2016
-	echo -e '\t-i\tSpecify the release image to be used in the build. By default, the image is determined using `openshift-install`, provided it is in $PATH'
+	echo -e '\t-i\tSpecify the installer binary. Will search in $PATH if neither -i nor -r are passed.'
+	echo -e '\t-r\tSpecify the build image. Mutually exclusive with -i.'
+	echo
 	echo -e '\tauthfile\tPath of the pull secret.'
+	echo
 	echo -e '\t-h\tPrint this help'
 }
 
@@ -72,15 +85,21 @@ collect_image_references() {
 ### Done with declarations, start doing something
 
 # Parse flags
-while getopts i:h opt; do
+while getopts r:i:h opt; do
 	case "$opt" in
-		i) release_image="$OPTARG" ;;
+		r) release_image="$OPTARG" ;;
+		i) installer="$OPTARG"     ;;
 		h) print_help; exit 0      ;;
 		*) unknown_flag            ;;
 	esac
 done
 
 shift "$((OPTIND-1))"
+
+if [ -n "$release_image" ] && [ -n "$installer" ]; then
+	>&2 echo "Fatal error: -r and -i are mutually exclusive."
+	exit 2
+fi
 
 if [ "$#" -ne 1 ]; then
 	>&2 echo "Fatal error: Wrong number of positional arguments; expected 1, got $#."
@@ -89,7 +108,6 @@ fi
 
 authfile="$1"
 
-# Validate inputs
 if [ -z "$authfile" ]; then
 	>&2 echo 'Fatal error: Missing the pull secret filename'
 	exit 2
@@ -102,7 +120,7 @@ fi
 
 
 # If release_image is not specified with the "-i" flag, then ask openshift-install
-release_image="${release_image:-$(get_installer_release_image)}"
+release_image="${release_image:-$(get_installer_release_image "$installer")}"
 if [ -z "$release_image" ]; then
 	>&2 echo ' Fatal error: Could not find the release image'
 	exit 2
